### PR TITLE
Convert nb to jupyter

### PR DESCRIPTION
**Pull request by hadim**
.bkr files will be deprecated soon so I have converted them all to .ipynb with a Beaker tool (https://github.com/twosigma/beakerx/blob/master/beaker/bkr2ipynb.py).

I have also moved all the notebook folders to `notebooks/`. Make more sense in my opinion but I can still undo it if needed.

### CODE REVIEW

**Comment by ctrueden** [comment]
@hadim Thanks very much for doing the conversion!

Unfortunately, it looks like the actual conversion commit, 6eabedc4be2f8f84825e1bdef15ca1939d065818, did not actually get all the notebooks, probably due to special characters in the filenames:
```
D       notebooks/[1] Using ImageJ/[1.01] Fundamentals of ImageJ.bkr
D       notebooks/[1] Using ImageJ/[1.02] Introduction to ImageJ Ops.bkr
D       notebooks/[1] Using ImageJ/[1.03] N-dimensional image processing.bkr
D       notebooks/[1] Using ImageJ/[1.05] Mixed World - Using ImageJ 1.x.bkr
A       notebooks/[1] Using ImageJ/[1.ipynb
D       notebooks/[2] Extending ImageJ/[2.01] Scripting.bkr
D       notebooks/[2] Extending ImageJ/[2.02] Writing I-O plugins.bkr
D       notebooks/[2] Extending ImageJ/[2.03] Writing Command plugins.bkr
D       notebooks/[2] Extending ImageJ/[2.04] Writing Op plugins.bkr
D       notebooks/[2] Extending ImageJ/[2.05] Writing Tool plugins.bkr
A       notebooks/[2] Extending ImageJ/[2.ipynb
D       notebooks/[3] Advanced usage/[3.01] The Architecture of SciJava.bkr
D       notebooks/[3] Advanced usage/[3.02] Under the hood - SciJava.bkr
A       notebooks/[3] Advanced usage/[3.ipynb
```
I tried rerunning the `bkr2ipynb.py` script, but I cannot make it work on my macOS or Linux systems.

On Linux:
```
$ ~/code/jupyter/beakerx/beaker/bkr2ipynb.py '[1.01] Fundamentals of ImageJ.bkr'
/home/curtis/code/jupyter/beakerx/beaker/bkr2ipynb.py: 18: /home/curtis/code/jupyter/beakerx/beaker/bkr2ipynb.py: Create a notebook containing code from a beaker notebook.

Run as:  python bkr2ipynb.py [notebook name].bkr
: not found
import: unable to open X server `' @ error/import.c/ImportImageCommand/366.
import: unable to open X server `' @ error/import.c/ImportImageCommand/366.
import: unable to open X server `' @ error/import.c/ImportImageCommand/366.
import: unable to open X server `' @ error/import.c/ImportImageCommand/366.
from: can't read /var/mail/nbformat.v4
/home/curtis/code/jupyter/beakerx/beaker/bkr2ipynb.py: 25: /home/curtis/code/jupyter/beakerx/beaker/bkr2ipynb.py: Syntax error: "(" unexpected
$ python ~/code/jupyter/beakerx/beaker/bkr2ipynb.py '[1.01] Fundamentals of ImageJ.bkr'
Traceback (most recent call last):
  File "/home/curtis/code/jupyter/beakerx/beaker/bkr2ipynb.py", line 21, in <module>
    import nbformat
ImportError: No module named nbformat
$ python3 ~/code/jupyter/beakerx/beaker/bkr2ipynb.py '[1.01] Fundamentals of ImageJ.bkr'
Traceback (most recent call last):
  File "/home/curtis/code/jupyter/beakerx/beaker/bkr2ipynb.py", line 21, in <module>
    import nbformat
ImportError: No module named nbformat
```

On macOS:
```
~/code/jupyter/beakerx/beaker/bkr2ipynb.py '[1.01] Fundamentals of ImageJ.bkr'                                                                                                                                   #  2 {2017-05-16 12:40:30}
/Users/curtis/code/jupyter/beakerx/beaker/bkr2ipynb.py: line 18: Create a notebook containing code from a beaker notebook.

Run as:  python bkr2ipynb.py [notebook name].bkr
: command not found
Version: ImageMagick 7.0.5-5 Q16 x86_64 2017-04-25 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
Usage: import [options ...] [ file ]

Image Settings:
  -adjoin              join images into a single multi-image file
  -border              include window border in the output image
  -channel type        apply option to select image channels
  -colorspace type     alternate image colorspace
  -comment string      annotate image with comment
  -compress type       type of pixel compression when writing the image
  -define format:option
                       define one or more image format options
  -density geometry    horizontal and vertical density of the image
  -depth value         image depth
  -descend             obtain image by descending window hierarchy
  -display server      X server to contact
  -dispose method      layer disposal method
  -dither method       apply error diffusion to image
  -delay value         display the next image after pausing
  -encipher filename   convert plain pixels to cipher pixels
  -endian type         endianness (MSB or LSB) of the image
  -encoding type       text encoding type
  -filter type         use this filter when resizing an image
  -format "string"     output formatted image characteristics
  -frame               include window manager frame
  -gravity direction   which direction to gravitate towards
  -identify            identify the format and characteristics of the image
  -interlace type      None, Line, Plane, or Partition
  -interpolate method  pixel color interpolation method
  -label string        assign a label to an image
  -limit type value    Area, Disk, Map, or Memory resource limit
  -monitor             monitor progress
  -page geometry       size and location of an image canvas
  -pause seconds       seconds delay between snapshots
  -pointsize value     font point size
  -quality value       JPEG/MIFF/PNG compression level
  -quiet               suppress all warning messages
  -regard-warnings     pay attention to warning messages
  -respect-parentheses settings remain in effect until parenthesis boundary
  -sampling-factor geometry
                       horizontal and vertical sampling factor
  -scene value         image scene number
  -screen              select image from root window
  -seed value          seed a new sequence of pseudo-random numbers
  -set property value  set an image property
  -silent              operate silently, i.e. don't ring any bells
  -snaps value         number of screen snapshots
  -support factor      resize support: > 1.0 is blurry, < 1.0 is sharp
  -synchronize         synchronize image to storage device
  -taint               declare the image as modified
  -transparent-color color
                       transparent color
  -treedepth value     color tree depth
  -verbose             print detailed information about the image
  -virtual-pixel method
                       Constant, Edge, Mirror, or Tile
  -window id           select window with this id or name

Image Operators:
  -annotate geometry text
                       annotate the image with text
  -colors value        preferred number of colors in the image
  -crop geometry       preferred size and location of the cropped image
  -encipher filename   convert plain pixels to cipher pixels
  -geometry geometry   preferred size or location of the image
  -help                print program options
  -monochrome          transform image to black and white
  -negate              replace every pixel with its complementary color
  -repage geometry     size and location of an image canvas
  -quantize colorspace reduce colors in this colorspace
  -resize geometry     resize the image
  -rotate degrees      apply Paeth rotation to the image
  -strip               strip image of all profiles and comments
  -thumbnail geometry  create a thumbnail of the image
  -transparent color   make this color transparent within the image
  -trim                trim image edges
  -type type           image type

Miscellaneous Options:
  -debug events        display copious debugging information
  -help                print program options
  -list type           print a list of supported option arguments
  -log format          format of debugging information
  -version             print version information

By default, 'file' is written in the MIFF image format.  To
specify a particular image format, precede the filename with an image
format name and a colon (i.e. ps:image) or specify the image type as
the filename suffix (i.e. image.ps).  Specify 'file' as '-' for
standard input or output.
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1294.
Version: ImageMagick 7.0.5-5 Q16 x86_64 2017-04-25 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
Usage: import [options ...] [ file ]

Image Settings:
  -adjoin              join images into a single multi-image file
  -border              include window border in the output image
  -channel type        apply option to select image channels
  -colorspace type     alternate image colorspace
  -comment string      annotate image with comment
  -compress type       type of pixel compression when writing the image
  -define format:option
                       define one or more image format options
  -density geometry    horizontal and vertical density of the image
  -depth value         image depth
  -descend             obtain image by descending window hierarchy
  -display server      X server to contact
  -dispose method      layer disposal method
  -dither method       apply error diffusion to image
  -delay value         display the next image after pausing
  -encipher filename   convert plain pixels to cipher pixels
  -endian type         endianness (MSB or LSB) of the image
  -encoding type       text encoding type
  -filter type         use this filter when resizing an image
  -format "string"     output formatted image characteristics
  -frame               include window manager frame
  -gravity direction   which direction to gravitate towards
  -identify            identify the format and characteristics of the image
  -interlace type      None, Line, Plane, or Partition
  -interpolate method  pixel color interpolation method
  -label string        assign a label to an image
  -limit type value    Area, Disk, Map, or Memory resource limit
  -monitor             monitor progress
  -page geometry       size and location of an image canvas
  -pause seconds       seconds delay between snapshots
  -pointsize value     font point size
  -quality value       JPEG/MIFF/PNG compression level
  -quiet               suppress all warning messages
  -regard-warnings     pay attention to warning messages
  -respect-parentheses settings remain in effect until parenthesis boundary
  -sampling-factor geometry
                       horizontal and vertical sampling factor
  -scene value         image scene number
  -screen              select image from root window
  -seed value          seed a new sequence of pseudo-random numbers
  -set property value  set an image property
  -silent              operate silently, i.e. don't ring any bells
  -snaps value         number of screen snapshots
  -support factor      resize support: > 1.0 is blurry, < 1.0 is sharp
  -synchronize         synchronize image to storage device
  -taint               declare the image as modified
  -transparent-color color
                       transparent color
  -treedepth value     color tree depth
  -verbose             print detailed information about the image
  -virtual-pixel method
                       Constant, Edge, Mirror, or Tile
  -window id           select window with this id or name

Image Operators:
  -annotate geometry text
                       annotate the image with text
  -colors value        preferred number of colors in the image
  -crop geometry       preferred size and location of the cropped image
  -encipher filename   convert plain pixels to cipher pixels
  -geometry geometry   preferred size or location of the image
  -help                print program options
  -monochrome          transform image to black and white
  -negate              replace every pixel with its complementary color
  -repage geometry     size and location of an image canvas
  -quantize colorspace reduce colors in this colorspace
  -resize geometry     resize the image
  -rotate degrees      apply Paeth rotation to the image
  -strip               strip image of all profiles and comments
  -thumbnail geometry  create a thumbnail of the image
  -transparent color   make this color transparent within the image
  -trim                trim image edges
  -type type           image type

Miscellaneous Options:
  -debug events        display copious debugging information
  -help                print program options
  -list type           print a list of supported option arguments
  -log format          format of debugging information
  -version             print version information

By default, 'file' is written in the MIFF image format.  To
specify a particular image format, precede the filename with an image
format name and a colon (i.e. ps:image) or specify the image type as
the filename suffix (i.e. image.ps).  Specify 'file' as '-' for
standard input or output.
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1294.
Version: ImageMagick 7.0.5-5 Q16 x86_64 2017-04-25 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
Usage: import [options ...] [ file ]

Image Settings:
  -adjoin              join images into a single multi-image file
  -border              include window border in the output image
  -channel type        apply option to select image channels
  -colorspace type     alternate image colorspace
  -comment string      annotate image with comment
  -compress type       type of pixel compression when writing the image
  -define format:option
                       define one or more image format options
  -density geometry    horizontal and vertical density of the image
  -depth value         image depth
  -descend             obtain image by descending window hierarchy
  -display server      X server to contact
  -dispose method      layer disposal method
  -dither method       apply error diffusion to image
  -delay value         display the next image after pausing
  -encipher filename   convert plain pixels to cipher pixels
  -endian type         endianness (MSB or LSB) of the image
  -encoding type       text encoding type
  -filter type         use this filter when resizing an image
  -format "string"     output formatted image characteristics
  -frame               include window manager frame
  -gravity direction   which direction to gravitate towards
  -identify            identify the format and characteristics of the image
  -interlace type      None, Line, Plane, or Partition
  -interpolate method  pixel color interpolation method
  -label string        assign a label to an image
  -limit type value    Area, Disk, Map, or Memory resource limit
  -monitor             monitor progress
  -page geometry       size and location of an image canvas
  -pause seconds       seconds delay between snapshots
  -pointsize value     font point size
  -quality value       JPEG/MIFF/PNG compression level
  -quiet               suppress all warning messages
  -regard-warnings     pay attention to warning messages
  -respect-parentheses settings remain in effect until parenthesis boundary
  -sampling-factor geometry
                       horizontal and vertical sampling factor
  -scene value         image scene number
  -screen              select image from root window
  -seed value          seed a new sequence of pseudo-random numbers
  -set property value  set an image property
  -silent              operate silently, i.e. don't ring any bells
  -snaps value         number of screen snapshots
  -support factor      resize support: > 1.0 is blurry, < 1.0 is sharp
  -synchronize         synchronize image to storage device
  -taint               declare the image as modified
  -transparent-color color
                       transparent color
  -treedepth value     color tree depth
  -verbose             print detailed information about the image
  -virtual-pixel method
                       Constant, Edge, Mirror, or Tile
  -window id           select window with this id or name

Image Operators:
  -annotate geometry text
                       annotate the image with text
  -colors value        preferred number of colors in the image
  -crop geometry       preferred size and location of the cropped image
  -encipher filename   convert plain pixels to cipher pixels
  -geometry geometry   preferred size or location of the image
  -help                print program options
  -monochrome          transform image to black and white
  -negate              replace every pixel with its complementary color
  -repage geometry     size and location of an image canvas
  -quantize colorspace reduce colors in this colorspace
  -resize geometry     resize the image
  -rotate degrees      apply Paeth rotation to the image
  -strip               strip image of all profiles and comments
  -thumbnail geometry  create a thumbnail of the image
  -transparent color   make this color transparent within the image
  -trim                trim image edges
  -type type           image type

Miscellaneous Options:
  -debug events        display copious debugging information
  -help                print program options
  -list type           print a list of supported option arguments
  -log format          format of debugging information
  -version             print version information

<Long ImageMagick usage output here>

import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1294.
from: can't read /var/mail/nbformat.v4
/Users/curtis/code/jupyter/beakerx/beaker/bkr2ipynb.py: line 25: syntax error near unexpected token `('
/Users/curtis/code/jupyter/beakerx/beaker/bkr2ipynb.py: line 25: `parser = argparse.ArgumentParser()'
```

Would you be willing to rerun the conversion across all the notebooks listed above, so that the filenames do not get mangled?

**Comment by hadim** [comment]
Can I rename the notebook ? `[` looks very bad in a filename !

**Comment by ctrueden** [comment]
@hadim Rename them if you want, sure.

**Comment by ctrueden** [comment]
Why did you delete the branch? You know you can just force push, right?

**Comment by hadim** [comment]
I messed up with git. I'll open a new PR.

**Comment by hadim** [comment]
I know I know, I just messed up :-)

**Comment by ctrueden** [comment]
All right. Thank you.

**Pull request closed without merging**
