### PR TITLE
Add ops

### PR DESCRIPTION
**Pull request by kkangle**
Added deconvolution ops example for multiple iterations, noncircular and accelerate.

### CODE REVIEW

**Comment by ctrueden** [comment]
We'll hold off merging this until after the remaining new ops from 0.39.0 are added as well.

**Comment by bnorthan** [comment]
It looks like the examples with the non-circulant deconvolution option=true returned an empty image.  This was fixed in the latest version of ops. So when you update ops those examples should work.  Let me know if there is still any issue with them.  If you need a reference I posted the groovy script with those examples here https://gist.github.com/bnorthan/eeed3663a4f7cad534c2bbb91d2e9b00.

**Comment by ctrueden** [comment]
Thanks @bnorthan. Relatedly, in case you didn't notice, I inlined the "DivideHandleZero" ops as inner classes of the deconvolution-related classes that actually use them.

**Comment by imagejan** [comment]
The Ops notebook is getting a bit big now. How about splitting it into several parts? Maybe a "real" introduction, and then some other notebooks to show off certain ops etc.? Or do think that is too much scatter?

**Comment by kkangle** [comment]
Thanks, @imagejan. I have talked to @ctrueden about this. We are going to rearrange it to an introduction notebook with links to specific ops as you suggested. It would certainly be easier to read this way. If you feel like there is a better way, please let me know.

**Pull request merged**
